import React from 'react';
import { Link } from 'react-router-dom';
import Footer from '../../layouts/Footer';

const Section = ({ title, children }) => (
  <div>
    <h2 className="text-xl font-semibold text-[color:var(--color-gradient-start)] mt-6 mb-3">{title}</h2>
    <div className="space-y-4">{children}</div>
  </div>
);

const Terms = () => (
  <div className="bg-black text-white min-h-screen pt-20">
    <div className="max-w-6xl mx-auto px-4 sm:px-6 md:px-8 py-12">
      <h1 className="text-4xl md:text-5xl font-bold text-gradient mb-8">
        Terms & Conditions
      </h1>
      <div className="space-y-6 text-base md:text-lg text-gray-300 leading-relaxed">
        <p>
          This document is an electronic record in accordance with the provisions of the Information Technology Act, 2000, and rules thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>

        <Section title="1. ELECTRONIC PLATFORM:">
          <p>
            The domain name [eleqt.in] ("Website") and the mobile application ("Application") are owned and operated by M/s Psynuxsoftware Private Limited, a company incorporated under the Companies Act, 2013 ("Eleqt" or "Company").
          </p>
        </Section>

        <Section title="2. ACCEPTANCE OF TERMS:">
          <p>2.1 These Terms and Conditions ("Terms") constitute a legally binding agreement between the User ("You") and Eleqt. By accessing the Website, registering on the Application, or using any of the services provided by ELEQT ("Services"), You agree to be bound by these Terms.</p>
          <p>2.2 If You do not agree to these Terms, please refrain from using our Services.</p>
          <p>2.3 Eleqt reserves the right to update or amend these Terms at any time. Continued use of the Platform after changes constitutes acceptance.</p>
        </Section>

        <Section title="3. DEFINITIONS:">
          <p>3.1 "Account" means the User’s registered profile with Eleqt.</p>
          <p>3.2 "Ride" or "Booking" means the vehicle ride facilitated through the Eleqt Platform.</p>
          <p>3.3 "Vehicle" means the vehicle offered under Eleqt services.</p>
          <p>3.4 "Total Ride Fee" includes base fare, applicable taxes, toll duty, parking, and convenience fees.</p>
        </Section>

        <Section title="4. USER ACCOUNT & ELIGIBILITY:">
          <p>4.1 Users must be 18+ years old and legally eligible to use services.</p>
          <p>4.2 Users must provide accurate personal information, including name, mobile number, and payment details.</p>
          <p>4.3 Users are responsible for the confidentiality of their login credentials.</p>
          <p>4.4 As part of the registration process, you agree to receive such marketing and promotional materials via mail, SMS, and/or email as we may deem appropriate to send you in connection with our Website and Services. For further details relating to the same, please refer to our Privacy Policy.</p>
        </Section>

        <Section title="5. SERVICES:">
          <p>5.1 Eleqt connects Users with mobility services by using premium vehicles.</p>
          <p>5.2 Rides are subject to vehicle availability, location, and local conditions.</p>
          <p>5.3 User agrees to: Use the service for lawful purposes, not damage the vehicle or disturb the driver, and avoid misuse, harassment, or fraudulent activity.</p>
        </Section>

        <Section title="6. TRAVELLING WITH PETS:">
            <p>6.1 No more than 2 pets are allowed to travel on a ride.</p>
            <p>6.2 Pets should be in carriers or under other suitable restraints at all times.</p>
            <p>6.3 Any damage done to the car by the pet(s) will be paid for by the guest in full.</p>
        </Section>

        <Section title="7. ADVERTISEMENT AND LINKS:">
            <p>7.1 Eleqt may periodically send promotional emails, SMSs, or push notifications to the User about its Services.</p>
            <p>7.2 Eleqt also reserves the right to reject or refuse any third-party service used by the User in conjunction with Eleqt's Electronic Media.</p>
        </Section>

        <Section title="8. CUSTOMER RELATIONSHIP MANAGEMENT:">
            <p>8.1 All issues, opinions, suggestions, questions, and feedback while availing of Eleqt's Services shall be communicated to us through the following email address: eleqtmobility@gmail.com</p>
            <p>8.2 Reporting of any issue needs to be within 7 (seven) days of the occurrence of the issue, failing which, such issue will not be addressed. The User agrees and acknowledges that any issues/complaints/grievances a User has must be communicated to Eleqt only through the Electronic Media or to the consumer helpdesk as stipulated in these Terms of Use of the Electronic Media and not on any other third-party platform/social media channels.</p>
            <p>8.3 The User shall be responsible and liable in respect of the wrongful allegation made and any issues posted on such other third-party platforms/social media.</p>
            <p>8.4 Eleqt takes no liability for the inability to get back or respond to any complaints made or content posted by the User about Eleqt on other channels.</p>
        </Section>

        <Section title="9. PAYMENT TERMS:">
          <p>9.1 Users agree to pay the full fare as displayed or notified during Booking.</p>
          <p>9.2 Payments may be made via cash, UPI, cards, or integrated payment gateways.</p>
          <p>9.3 Additional charges may apply for waiting time, location-specific tolls, or damage.</p>
        </Section>

        <Section title="10. CANCELLATION & REFUND:">
          <p>10.1 Bookings may be cancelled before the ride starts; charges may apply for late cancellations.</p>
          <p>10.2 Refunds, if applicable, will be processed to the original payment method.</p>
        </Section>

        <Section title="11. LIABILITY AND LIMITATION:">
          <p>11.1 Eleqt is not responsible for delays caused by traffic, weather, mechanical failure, or other Force Majeure Events.</p>
          <p>11.2 Eleqt is not liable for loss of personal belongings left in vehicles.</p>
          <p>11.3 Our total liability is limited to the Total Ride Fee for the disputed Ride.</p>
        </Section>

        <Section title="12. INTELLECTUAL PROPERTY:">
          <p>12.1 All content, trademarks, logos, and software on the Platform belong to Eleqt or its licensors.</p>
          <p>12.2 Users may not reproduce, copy, modify, or distribute any content without permission.</p>
        </Section>

        <Section title="13. USER CONDUCT:">
          <ul className="list-disc list-inside space-y-2">
            <li>Maintain respectful behavior with drivers and support staff</li>
            <li>Do not smoke, drink alcohol, or carry illegal items</li>
            <li>Be responsible for their safety and conduct during the Ride</li>
          </ul>
        </Section>
        
        <Section title="14. TERMINATION:">
            <p>Eleqt may suspend or terminate a User’s account for violations of these Terms, fraudulent behavior, or misuse of services.</p>
        </Section>

        <Section title="15. DATA PRIVACY:">
          <p>
            Personal information is collected, stored, and used as per our <Link to="/privacy-policy" className="text-pink-300 hover:underline">Privacy Policy</Link>.
          </p>
        </Section>

        <Section title="16. GOVERNING LAW AND DISPUTES:">
            <p>16.1 These Terms are governed by the laws of India.</p>
            <p>16.2 All disputes arising out of or in connection with the Terms of Use shall be attempted to be settled through negotiation between senior management of the Company and the User. If any dispute arising between the parties is not amicably settled within a reasonable period of sixty (60) days of the initiation of the aforesaid dispute resolution mechanisms, then, the same shall be resolved by arbitration following the provisions of the Rules of Arbitration of the Indian Council of Arbitration for the time being in force, which rules shall be deemed to be incorporated by reference in this Clause (16). The dispute shall be referred to one (1) arbitrator to be appointed/ nominated by the Company. The language of the arbitration will be English. The decision of the arbitrator will be final, binding, and incontestable and may be used as a basis for judgment thereon in India or elsewhere. The Company and the User will bear their own costs of the arbitration.</p>
            <p>16.3 All disputes shall be subject to the jurisdiction of the courts in Bhubaneswar, Odisha.</p>
        </Section>

        <Section title="17. CONTACT US:">
            <p>For questions or support, contact us at: Email: eleqtmobility@gmail.com</p>
            <p>Eleqt Mobility | M/s Psynuxsoftware Pvt. Ltd.</p>
        </Section>

      </div>
    </div>
    <Footer bgColor="bg-gray-900" />
  </div>
);

export default Terms;
